<?php
/**
 * ダミー商品データ（フロント確認用）。
 * 将来的にDB化する場合はこのファイルをリポジトリ層に置き換える想定。
 */

$categories = [
    'ring'      => 'リング',
    'pendant'   => 'ペンダント',
    'bangle'    => 'バングル',
    'dogtag'    => 'ドッグタグ',
    'bracelet'  => 'ブレスレット',
    'earring'   => 'ピアス',
];

$img_base = '/assets/img/';

$products = [
    [
        'id' => 1,
        'name' => '天使の羽リング',
        'category' => 'ring',
        'price' => 39800,
        'image' => $img_base . 'ring.jpg',
        'worn_image' => $img_base . 'ring.jpg',
        'pickup' => false,
        'new' => false,
        'engravable' => false,
        'description' => "天使の羽を立体的に表現したシルバーリング。燻し加工による深い陰影が、指元に重厚感を与えます。",
        'material' => 'Silver925',
    ],
    [
        'id' => 2,
        'name' => '彼岸花リング',
        'category' => 'ring',
        'price' => 34800,
        'image' => $img_base . 'ring.svg',
        'worn_image' => $img_base . 'hand-ring.svg',
        'pickup' => false,
        'new' => false,
        'engravable' => false,
        'description' => "妖しく咲く彼岸花を立体的に表現したシルバーリング。繊細な花弁と燻しの陰影が、指元に儚く重厚な存在感を与えます。",
        'material' => 'Silver925',
    ],
    [
        'id' => 28,
        'name' => '鴉の爪リング',
        'category' => 'ring',
        'price' => 39800,
        'image' => $img_base . 'ring.svg',
        'worn_image' => $img_base . 'hand-ring.svg',
        'pickup' => false,
        'new' => false,
        'engravable' => false,
        'description' => "指を捕らえる鴉の爪を立体的に表現したシルバーリング。鋭い造形と燻しの陰影が、指元にダークな重厚感を与えます。",
        'material' => 'Silver925',
    ],
    [
        'id' => 29,
        'name' => 'ダブルハートリング',
        'category' => 'ring',
        'price' => 39800,
        'image' => $img_base . 'ring.svg',
        'worn_image' => $img_base . 'hand-ring.svg',
        'pickup' => false,
        'new' => false,
        'engravable' => false,
        'description' => "二つのハートが溶け合うように重なるシルバーリング。流れるような曲線と燻しの陰影が、指元に繊細な存在感を与えます。",
        'material' => 'Silver925',
    ],
    [
        'id' => 30,
        'name' => '黒リボンリング',
        'category' => 'ring',
        'price' => 34800,
        'image' => $img_base . 'ring.svg',
        'worn_image' => $img_base . 'hand-ring.svg',
        'pickup' => false,
        'new' => false,
        'engravable' => false,
        'description' => "可憐なリボンを深い燻しでダークに仕上げたシルバーリング。繊細な結び目と陰影が、指元に甘さと退廃的な存在感を与えます。",
        'material' => 'Silver925',
    ],
    [
        'id' => 31,
        'name' => '輪廻リング',
        'category' => 'ring',
        'price' => 39800,
        'image' => $img_base . 'ring.svg',
        'worn_image' => $img_base . 'hand-ring.svg',
        'pickup' => false,
        'new' => false,
        'engravable' => false,
        'description' => "幾重にも広がる円環模様を全面に刻んだシルバーリング。深い燻しが模様を際立たせ、指元に重厚で幻想的な存在感を与えます。",
        'material' => 'Silver925',
    ],
    [
        'id' => 32,
        'name' => '∞リング',
        'category' => 'ring',
        'price' => 34800,
        'image' => $img_base . 'ring.svg',
        'worn_image' => $img_base . 'hand-ring.svg',
        'pickup' => false,
        'new' => false,
        'engravable' => false,
        'description' => "終わりなく巡る無限の輪を、滑らかな曲線で表現したシルバーリング。鏡面の輝きと立体的な造形が、指元に静かな存在感を与えます。",
        'material' => 'Silver925',
    ],
    [
        'id' => 33,
        'name' => '欠落のピースリング',
        'category' => 'ring',
        'price' => 49800,
        'image' => $img_base . 'ring.svg',
        'worn_image' => $img_base . 'hand-ring.svg',
        'pickup' => false,
        'new' => false,
        'engravable' => false,
        'description' => "幾つものパズルピースが噛み合う姿を表現したSilver925リング。荒れた質感と深い燻しが、指元に未完成ゆえの重厚な存在感を与えます。",
        'material' => 'Silver925',
    ],
    [
        'id' => 34,
        'name' => '竹節リング',
        'category' => 'ring',
        'price' => 39800,
        'image' => $img_base . 'ring.svg',
        'worn_image' => $img_base . 'hand-ring.svg',
        'pickup' => false,
        'new' => false,
        'engravable' => false,
        'description' => "しなやかに絡み合う竹と節の造形を一周に施したSilver925リング。深い燻しと力強い曲線が、指元に静かで生命力のある存在感を与えます。",
        'material' => 'Silver925',
    ],
    [
        'id' => 35,
        'name' => '天使の羽バングル',
        'category' => 'bangle',
        'price' => 69800,
        'image' => $img_base . 'bangle.svg',
        'worn_image' => $img_base . 'wrist-bangle.svg',
        'pickup' => false,
        'new' => false,
        'engravable' => false,
        'description' => "幾重にも重なる羽根を繊細に彫り込んだSilver925バングル。深い燻しと立体的な造形が、腕元に力強く神秘的な存在感を与えます。",
        'material' => 'Silver925',
    ],
    [
        'id' => 36,
        'name' => '螺旋バングル',
        'category' => 'bangle',
        'price' => 69800,
        'image' => $img_base . 'bangle.svg',
        'worn_image' => $img_base . 'wrist-bangle.svg',
        'pickup' => false,
        'new' => false,
        'engravable' => false,
        'description' => "終わりなく続く螺旋模様を全面に刻んだSilver925バングル。深い燻しと反復する曲線が、腕元に吸い込まれるような存在感を与えます。",
        'material' => 'Silver925',
    ],
    [
        'id' => 37,
        'name' => '黒薔薇バングル',
        'category' => 'bangle',
        'price' => 79800,
        'image' => $img_base . 'bangle.svg',
        'worn_image' => $img_base . 'wrist-bangle.svg',
        'pickup' => false,
        'new' => false,
        'engravable' => false,
        'description' => "闇に咲く黒薔薇を連続して刻み込んだSilver925バングル。深い燻しと緻密な装飾が、腕元に気高く退廃的な存在感を与えます。",
        'material' => 'Silver925',
    ],
    [
        'id' => 38,
        'name' => '渦潮バングル',
        'category' => 'bangle',
        'price' => 59800,
        'image' => $img_base . 'bangle.svg',
        'worn_image' => $img_base . 'wrist-bangle.svg',
        'pickup' => false,
        'new' => false,
        'engravable' => false,
        'description' => "荒れ狂う潮の渦を連続する曲線で表現したSilver925バングル。深い燻しと透かし彫りの陰影が、腕元に荒々しく神秘的な存在感を与えます。",
        'material' => 'Silver925',
    ],
    [
        'id' => 39,
        'name' => 'ダブルハートバングル',
        'category' => 'bangle',
        'price' => 49800,
        'image' => $img_base . 'bangle.svg',
        'worn_image' => $img_base . 'wrist-bangle.svg',
        'pickup' => false,
        'new' => false,
        'engravable' => false,
        'description' => "二つのハートが溶け合うように重なるSilver925バングル。滑らかな曲線と燻しの陰影が、腕元に繊細で儚い存在感を与えます。",
        'material' => 'Silver925',
    ],
    [
        'id' => 40,
        'name' => '竹節バングル',
        'category' => 'bangle',
        'price' => 59800,
        'image' => $img_base . 'bangle.svg',
        'worn_image' => $img_base . 'wrist-bangle.svg',
        'pickup' => false,
        'new' => false,
        'engravable' => false,
        'description' => "しなやかに絡み合う竹と節の造形を表現したSilver925バングル。深い燻しと力強い曲線が、腕元に静かで生命力のある存在感を与えます。",
        'material' => 'Silver925',
    ],
    [
        'id' => 41,
        'name' => '双蛇の禁花バングル',
        'category' => 'bangle',
        'price' => 79800,
        'image' => $img_base . 'bangle.svg',
        'worn_image' => $img_base . 'wrist-bangle.svg',
        'pickup' => false,
        'new' => false,
        'engravable' => false,
        'description' => "禁断の花を守るように向かい合う二匹の蛇を刻んだSilver925バングル。深い燻しと緻密な彫刻が、腕元に妖しく荘厳な存在感を与えます。",
        'material' => 'Silver925',
    ],
    [
        'id' => 42,
        'name' => '禁断の蛇薔薇ブレスレット',
        'category' => 'bracelet',
        'price' => 129800,
        'image' => $img_base . 'bracelet.svg',
        'worn_image' => $img_base . 'wrist-bracelet.svg',
        'pickup' => false,
        'new' => false,
        'engravable' => false,
        'description' => "禁断の薔薇の間を蛇が絡み合うように連なるSilver925ブレスレット。精密な鱗と花弁、深い燻しが、腕元に妖艶で圧倒的な存在感を与えます。",
        'material' => 'Silver925',
    ],
];

/**
 * フロントのみのデザインモックのため、カートの中身は固定のサンプルデータ。
 * cart.php / checkout.php / order-complete.php で共通利用する。
 * 実装時はセッションやDBのカート情報に置き換える想定。
 */
$mock_cart_lines = [
    ['id' => 1, 'qty' => 1],
    ['id' => 2, 'qty' => 2],
    ['id' => 4, 'qty' => 1],
];

/**
 * フロントのみのデザインモックのため、マイページの注文履歴は固定のサンプルデータ。
 * 実装時はセッションやDBの注文情報に置き換える想定。
 */
$mock_orders = [
    [
        'number' => 'SV-20260810-1234',
        'date' => '2026-08-10',
        'status' => '発送済み',
        'lines' => [
            ['id' => 5, 'qty' => 1],
            ['id' => 19, 'qty' => 1],
        ],
    ],
    [
        'number' => 'SV-20260715-0231',
        'date' => '2026-07-15',
        'status' => '対応完了',
        'lines' => [
            ['id' => 2, 'qty' => 1],
        ],
    ],
];

/**
 * フロントのみのデザインモックのため、マイページの会員情報・お届け先住所も固定のサンプルデータ。
 */
$mock_member = [
    'name' => '山田 花子',
    'email' => 'hanako@example.com',
    'zip' => '000-0000',
    'address' => '東京都◯◯区◯◯ 0-0-0',
    'tel' => '000-0000-0000',
];
