<?php
/**
 * ダミー商品データ（フロント確認用）。
 * 将来的にDB化する場合はこのファイルをリポジトリ層に置き換える想定。
 */

$categories = [
    'ring'      => 'リング',
    'necklace'  => 'ネックレス',
    'bracelet'  => 'ブレスレット',
    'earring'   => 'ピアス',
];

$img_base = '/silver/assets/img/';

$products = [
    [
        'id' => 1,
        'name' => 'Thin Line Ring',
        'category' => 'ring',
        'price' => 12800,
        'image' => $img_base . 'ring.svg',
        'worn_image' => $img_base . 'hand-ring.svg',
        'pickup' => true,
        'new' => true,
        'description' => "細く華奢なラインだけで構成したミニマルなリング。\n重ね付けにも、単体でも馴染みます。",
        'material' => 'Silver925',
    ],
    [
        'id' => 2,
        'name' => 'Dew Necklace',
        'category' => 'necklace',
        'price' => 15800,
        'image' => $img_base . 'necklace.svg',
        'worn_image' => $img_base . 'neck-necklace.svg',
        'pickup' => true,
        'new' => true,
        'description' => "しずくのようなモチーフをあしらったネックレス。\n鎖骨のラインに沿う長さで設計しています。",
        'material' => 'Silver925',
    ],
    [
        'id' => 3,
        'name' => 'Curve Bangle',
        'category' => 'bracelet',
        'price' => 18800,
        'image' => $img_base . 'bracelet.svg',
        'worn_image' => $img_base . 'wrist-bracelet.svg',
        'pickup' => true,
        'new' => false,
        'description' => "手首の曲線に合わせた、継ぎ目の少ないバングル。\n単体使いでも存在感があります。",
        'material' => 'Silver925',
    ],
    [
        'id' => 4,
        'name' => 'Drop Earring',
        'category' => 'earring',
        'price' => 9800,
        'image' => $img_base . 'earring.svg',
        'worn_image' => $img_base . 'ear-earring.svg',
        'pickup' => true,
        'new' => true,
        'description' => "揺れるたびに光を拾うドロップ型のピアス。\n耳元を華奢に見せるバランスで作りました。",
        'material' => 'Silver925',
    ],
    [
        'id' => 5,
        'name' => 'Plain Band Ring',
        'category' => 'ring',
        'price' => 9800,
        'image' => $img_base . 'ring.svg',
        'worn_image' => $img_base . 'hand-ring.svg',
        'pickup' => false,
        'new' => false,
        'description' => "余分な装飾を削ぎ落としたプレーンなバンドリング。\n毎日の相棒になる一本。",
        'material' => 'Silver925',
    ],
    [
        'id' => 6,
        'name' => 'Facet Ring',
        'category' => 'ring',
        'price' => 13800,
        'image' => $img_base . 'ring.svg',
        'worn_image' => $img_base . 'hand-ring.svg',
        'pickup' => false,
        'new' => false,
        'description' => "small facet cut を施したリング。\n光の当たり方で表情が変わります。",
        'material' => 'Silver925',
    ],
    [
        'id' => 7,
        'name' => 'Layer Necklace',
        'category' => 'necklace',
        'price' => 17800,
        'image' => $img_base . 'necklace.svg',
        'worn_image' => $img_base . 'neck-necklace.svg',
        'pickup' => false,
        'new' => false,
        'description' => "二連のチェーンを一本にまとめたレイヤードデザイン。",
        'material' => 'Silver925',
    ],
    [
        'id' => 8,
        'name' => 'Chain Necklace',
        'category' => 'necklace',
        'price' => 14800,
        'image' => $img_base . 'necklace.svg',
        'worn_image' => $img_base . 'neck-necklace.svg',
        'pickup' => false,
        'new' => true,
        'description' => "シンプルなチェーンのみで魅せるネックレス。",
        'material' => 'Silver925',
    ],
    [
        'id' => 9,
        'name' => 'Thin Bangle',
        'category' => 'bracelet',
        'price' => 16800,
        'image' => $img_base . 'bracelet.svg',
        'worn_image' => $img_base . 'wrist-bracelet.svg',
        'pickup' => false,
        'new' => false,
        'description' => "細身でスタッキングしやすいバングル。",
        'material' => 'Silver925',
    ],
    [
        'id' => 10,
        'name' => 'Chain Bracelet',
        'category' => 'bracelet',
        'price' => 13800,
        'image' => $img_base . 'bracelet.svg',
        'worn_image' => $img_base . 'wrist-bracelet.svg',
        'pickup' => false,
        'new' => false,
        'description' => "手首に程よく沿うチェーンブレスレット。",
        'material' => 'Silver925',
    ],
    [
        'id' => 11,
        'name' => 'Small Hoop Earring',
        'category' => 'earring',
        'price' => 8800,
        'image' => $img_base . 'earring.svg',
        'worn_image' => $img_base . 'ear-earring.svg',
        'pickup' => false,
        'new' => false,
        'description' => "耳元に軽く添うスモールフープ。",
        'material' => 'Silver925',
    ],
    [
        'id' => 12,
        'name' => 'Stud Earring',
        'category' => 'earring',
        'price' => 7800,
        'image' => $img_base . 'earring.svg',
        'worn_image' => $img_base . 'ear-earring.svg',
        'pickup' => false,
        'new' => false,
        'description' => "どんな場面にも合わせやすいスタッドピアス。",
        'material' => 'Silver925',
    ],
    [
        'id' => 13,
        'name' => 'Pinky Ring',
        'category' => 'ring',
        'price' => 8800,
        'image' => $img_base . 'ring.svg',
        'worn_image' => $img_base . 'hand-ring.svg',
        'pickup' => false,
        'new' => false,
        'description' => "小指にちょうどよいサイズ感のリング。",
        'material' => 'Silver925',
    ],
    [
        'id' => 14,
        'name' => 'Double Line Ring',
        'category' => 'ring',
        'price' => 11800,
        'image' => $img_base . 'ring.svg',
        'worn_image' => $img_base . 'hand-ring.svg',
        'pickup' => false,
        'new' => true,
        'description' => "2本のラインを重ねたようなデザインリング。",
        'material' => 'Silver925',
    ],
    [
        'id' => 15,
        'name' => 'Petit Pendant',
        'category' => 'necklace',
        'price' => 12800,
        'image' => $img_base . 'necklace.svg',
        'worn_image' => $img_base . 'neck-necklace.svg',
        'pickup' => false,
        'new' => false,
        'description' => "小さなモチーフが揺れるプチペンダント。",
        'material' => 'Silver925',
    ],
    [
        'id' => 16,
        'name' => 'Choker Necklace',
        'category' => 'necklace',
        'price' => 13800,
        'image' => $img_base . 'necklace.svg',
        'worn_image' => $img_base . 'neck-necklace.svg',
        'pickup' => false,
        'new' => false,
        'description' => "首元にすっと沿うチョーカータイプ。",
        'material' => 'Silver925',
    ],
    [
        'id' => 17,
        'name' => 'Double Bangle',
        'category' => 'bracelet',
        'price' => 19800,
        'image' => $img_base . 'bracelet.svg',
        'worn_image' => $img_base . 'wrist-bracelet.svg',
        'pickup' => false,
        'new' => true,
        'description' => "重ね付けしたような二連デザインのバングル。",
        'material' => 'Silver925',
    ],
    [
        'id' => 18,
        'name' => 'Anklet Chain',
        'category' => 'bracelet',
        'price' => 10800,
        'image' => $img_base . 'bracelet.svg',
        'worn_image' => $img_base . 'wrist-bracelet.svg',
        'pickup' => false,
        'new' => false,
        'description' => "華奢なチェーンのアンクレットにもなる一本。",
        'material' => 'Silver925',
    ],
    [
        'id' => 19,
        'name' => 'Huggie Hoop Earring',
        'category' => 'earring',
        'price' => 9200,
        'image' => $img_base . 'earring.svg',
        'worn_image' => $img_base . 'ear-earring.svg',
        'pickup' => false,
        'new' => false,
        'description' => "耳元に沿う小ぶりなハギーフープ。",
        'material' => 'Silver925',
    ],
    [
        'id' => 20,
        'name' => 'Long Drop Earring',
        'category' => 'earring',
        'price' => 10800,
        'image' => $img_base . 'earring.svg',
        'worn_image' => $img_base . 'ear-earring.svg',
        'pickup' => false,
        'new' => true,
        'description' => "縦のラインを強調するロングドロップピアス。",
        'material' => 'Silver925',
    ],
];
